console.log();
console.log('\x1b[32m╔════════════════════════════════════════════════════════════════╗');
console.log('\x1b[32m║           \x1b[36mThanks for installing Discord Player Music!          \x1b[32m║');
console.log('\x1b[32m╠════════════════════════════════════════════════════════════════╣');
console.log('\x1b[32m║                   \x1b[37mImportant Information:                       \x1b[32m║');
console.log('\x1b[32m║       \x1b[35m Discord Server: https://discord.gg/zzbkvCcu2r           \x1b[32m║');
console.log('\x1b[32m║             \x1b[35mDocumentation: https://dpm-docs.tk                 \x1b[32m║');
console.log('\x1b[32m║              \x1b[35mDeveloper: ♡ xүℓ[ι]gαη4εg ♡#9457                  \x1b[32m║');
console.log('\x1b[32m╚════════════════════════════════════════════════════════════════╝\x1b[37m');
console.log();